import { Buffer } from 'node:buffer';
import { TCPClient, type TcpClientOptions } from './tcp_client.js';
import type { TcpConnection } from './tcp_connection.js';
export class HttpClientError extends Error { constructor(message: string, options?: ErrorOptions) { super(message, options); this.name = 'HttpClientError'; } }
export interface HttpClientOptions extends Omit<TcpClientOptions, 'secure' | 'serverName'> { maxRedirects?: number; maxHeaderSize?: number; maxBodySize?: number }
export interface HttpRequestOptions { headers?: Record<string, string | string[]>; body?: Buffer | Uint8Array | string; timeoutMs?: number; maxRedirects?: number }
export interface HttpResponse { uri: URL; version: string; statusCode: number; reasonPhrase: string; headers: Map<string, string[]>; body: Buffer; text(encoding?: BufferEncoding): string; json<T = unknown>(): T; header(name: string): string | undefined; isSuccess: boolean }
export function parseStatusLine(line: string): { version: string; statusCode: number; reasonPhrase: string } { const m = /^HTTP\/(\d(?:\.\d)?)\s+(\d{3})(?:\s+(.*))?$/.exec(line); if (!m?.[1] || !m[2]) throw new HttpClientError(`Invalid HTTP status line: ${line}`); return { version: m[1], statusCode: Number(m[2]), reasonPhrase: m[3] ?? '' }; }
export function parseHeaders(lines: string[]): Map<string, string[]> { const headers = new Map<string, string[]>(); for (const line of lines) { if (!line) continue; const idx = line.indexOf(':'); if (idx <= 0) throw new HttpClientError(`Invalid HTTP header line: ${line}`); const name = line.slice(0, idx).trim().toLowerCase(); const value = line.slice(idx + 1).trim(); headers.set(name, [...(headers.get(name) ?? []), value]); } return headers; }
export async function readChunkedBody(conn: TcpConnection, maxBodySize: number, timeoutMs?: number): Promise<Buffer> { const chunks: Buffer[] = []; let total = 0; for (;;) { const lineBuf = (await conn.readUntil(Buffer.from('\r\n'), 8192, timeoutMs)).data; const sizeText = lineBuf.subarray(0, -2).toString('latin1').split(';')[0]?.trim() ?? ''; const size = Number.parseInt(sizeText, 16); if (!Number.isFinite(size) || size < 0) throw new HttpClientError(`Invalid chunk size: ${sizeText}`); if (size === 0) { await conn.readUntil(Buffer.from('\r\n'), 8192, timeoutMs); break; } total += size; if (total > maxBodySize) throw new HttpClientError(`HTTP body exceeds ${maxBodySize} bytes`); chunks.push(await conn.readExact(size, timeoutMs)); await conn.readExact(2, timeoutMs); } return Buffer.concat(chunks, total); }
class ResponseImpl implements HttpResponse { constructor(public uri: URL, public version: string, public statusCode: number, public reasonPhrase: string, public headers: Map<string, string[]>, public body: Buffer) {} text(encoding: BufferEncoding = 'utf8'): string { return this.body.toString(encoding); } json<T = unknown>(): T { return JSON.parse(this.text()) as T; } header(name: string): string | undefined { return this.headers.get(name.toLowerCase())?.[0]; } get isSuccess(): boolean { return this.statusCode >= 200 && this.statusCode <= 299; } }
export class HttpClient {
  constructor(private readonly options: HttpClientOptions = {}) {}
  async request(method: string, url: string | URL, options: HttpRequestOptions = {}): Promise<HttpResponse> { return this.requestInner(method, new URL(url), options, options.maxRedirects ?? this.options.maxRedirects ?? 5); }
  get(url: string | URL, options?: HttpRequestOptions): Promise<HttpResponse> { return this.request('GET', url, options); }
  delete(url: string | URL, options?: HttpRequestOptions): Promise<HttpResponse> { return this.request('DELETE', url, options); }
  post(url: string | URL, body?: Buffer | Uint8Array | string, options: HttpRequestOptions = {}): Promise<HttpResponse> { return this.request('POST', url, { ...options, body }); }
  put(url: string | URL, body?: Buffer | Uint8Array | string, options: HttpRequestOptions = {}): Promise<HttpResponse> { return this.request('PUT', url, { ...options, body }); }
  patch(url: string | URL, body?: Buffer | Uint8Array | string, options: HttpRequestOptions = {}): Promise<HttpResponse> { return this.request('PATCH', url, { ...options, body }); }
  postJson(url: string | URL, value: unknown, options: HttpRequestOptions = {}): Promise<HttpResponse> { return this.post(url, JSON.stringify(value), { ...options, headers: { 'Content-Type': 'application/json', ...(options.headers ?? {}) } }); }
  private async requestInner(method: string, uri: URL, opts: HttpRequestOptions, redirectsLeft: number): Promise<HttpResponse> { if (!['http:', 'https:'].includes(uri.protocol)) throw new HttpClientError(`Unsupported protocol: ${uri.protocol}`); const secure = uri.protocol === 'https:'; const port = uri.port ? Number(uri.port) : secure ? 443 : 80; const conn = await new TCPClient({ ...this.options, timeoutMs: opts.timeoutMs ?? this.options.timeoutMs, secure, serverName: uri.hostname }).connect(uri.hostname, port); try { const body = opts.body === undefined ? undefined : Buffer.isBuffer(opts.body) ? opts.body : Buffer.from(opts.body); const headers = new Map<string, string[]>(); const add = (k: string, v: string | string[]) => headers.set(k.toLowerCase(), Array.isArray(v) ? v : [v]); add('Host', uri.port ? `${uri.hostname}:${uri.port}` : uri.hostname); add('Connection', 'close'); add('Accept-Encoding', 'identity'); for (const [k, v] of Object.entries(opts.headers ?? {})) { validateHeader(k, Array.isArray(v) ? v.join(', ') : v); add(k, v); } if (body) add('Content-Length', String(body.length)); const path = `${uri.pathname || '/'}${uri.search}`; let req = `${method.toUpperCase()} ${path} HTTP/1.1\r\n`; for (const [k, vals] of headers) for (const v of vals) req += `${canonical(k)}: ${v}\r\n`; req += '\r\n'; await conn.write(Buffer.concat([Buffer.from(req, 'utf8'), body ?? Buffer.alloc(0)])); const response = await this.readResponse(conn, uri, opts.timeoutMs ?? this.options.timeoutMs); const loc = response.header('location'); if ([301, 302, 303, 307, 308].includes(response.statusCode) && loc && redirectsLeft > 0) { await conn.end(); const next = new URL(loc, uri); const nextMethod = response.statusCode === 303 ? 'GET' : method; return this.requestInner(nextMethod, next, { ...opts, body: nextMethod === 'GET' ? undefined : opts.body }, redirectsLeft - 1); } return response; } finally { conn.destroy(); } }
  private async readResponse(conn: TcpConnection, uri: URL, timeoutMs?: number): Promise<HttpResponse> { const maxHeader = this.options.maxHeaderSize ?? 32 * 1024; const maxBody = this.options.maxBodySize ?? 10 * 1024 * 1024; const headerBuf = (await conn.readUntil(Buffer.from('\r\n\r\n'), maxHeader, timeoutMs)).data; const lines = headerBuf.toString('latin1').slice(0, -4).split('\r\n'); const status = parseStatusLine(lines[0] ?? ''); const headers = parseHeaders(lines.slice(1)); const header = (name: string) => headers.get(name.toLowerCase())?.[0]; let body: Buffer; const te = header('transfer-encoding')?.toLowerCase(); const cl = header('content-length'); if (te?.includes('chunked')) body = await readChunkedBody(conn, maxBody, timeoutMs); else if (cl !== undefined) { const len = Number(cl); if (!Number.isInteger(len) || len < 0) throw new HttpClientError('Invalid Content-Length'); if (len > maxBody) throw new HttpClientError(`HTTP body exceeds ${maxBody} bytes`); body = await conn.readExact(len, timeoutMs); } else body = await readUntilClose(conn, maxBody, timeoutMs); return new ResponseImpl(uri, status.version, status.statusCode, status.reasonPhrase, headers, body); }
}
function validateHeader(name: string, value: string): void { if (!/^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$/.test(name) || /[\r\n]/.test(value)) throw new HttpClientError('Invalid HTTP header'); }
function canonical(name: string): string { return name.split('-').map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('-'); }
async function readUntilClose(conn: TcpConnection, maxBody: number, timeoutMs?: number): Promise<Buffer> { const chunks: Buffer[] = []; let total = 0; for (;;) { try { const c = await conn.onceData(timeoutMs); total += c.length; if (total > maxBody) throw new HttpClientError(`HTTP body exceeds ${maxBody} bytes`); chunks.push(c); } catch { break; } } return Buffer.concat(chunks, total); }
