import { createHash, randomBytes } from 'node:crypto';
import { Buffer } from 'node:buffer';
import { TCPClient, type TcpClientOptions } from './tcp_client.js';
import type { TcpConnection } from './tcp_connection.js';
import { EventEmitter } from '../utils/event_emitter.js';
export enum WebSocketReadyState { connecting = 0, open = 1, closing = 2, closed = 3 }
export enum WebSocketOpcode { continuation = 0x0, text = 0x1, binary = 0x2, close = 0x8, ping = 0x9, pong = 0xa }
export interface WebSocketMessage { opcode: WebSocketOpcode; data: Buffer; text?: string }
export class WebSocketClientError extends Error { constructor(message: string, options?: ErrorOptions) { super(message, options); this.name = 'WebSocketClientError'; } }
type Events = { message: [WebSocketMessage]; text: [string]; binary: [Buffer]; ping: [Buffer]; pong: [Buffer]; close: [number | undefined, string | undefined]; error: [Error] };
export interface WebSocketClientOptions extends Omit<TcpClientOptions, 'secure' | 'serverName'> { headers?: Record<string, string>; protocols?: string[]; autoPong?: boolean; pingIntervalMs?: number; maxPayloadSize?: number }
interface Frame { fin: boolean; opcode: WebSocketOpcode; masked: boolean; payload: Buffer }
const GUID = '258EAFA5-E914-47DA-95CA-C5AB0DC85B11';
export function computeWebSocketAccept(key: string): string { return createHash('sha1').update(key + GUID).digest('base64'); }
export function encodeClosePayload(code?: number, reason = ''): Buffer { if (code === undefined) return Buffer.alloc(0); const reasonBytes = Buffer.from(reason, 'utf8'); const buf = Buffer.alloc(2 + reasonBytes.length); buf.writeUInt16BE(code, 0); reasonBytes.copy(buf, 2); return buf; }
export function decodeClosePayload(payload: Buffer): { code?: number; reason?: string } { if (payload.length < 2) return {}; return { code: payload.readUInt16BE(0), reason: payload.subarray(2).toString('utf8') }; }
export function encodeWebSocketFrame(opcode: WebSocketOpcode, payload: Buffer | Uint8Array | string = Buffer.alloc(0), masked = true): Buffer { const data = typeof payload === 'string' ? Buffer.from(payload, 'utf8') : Buffer.from(payload); const header: number[] = [0x80 | opcode]; const len = data.length; if (len < 126) header.push((masked ? 0x80 : 0) | len); else if (len <= 0xffff) header.push((masked ? 0x80 : 0) | 126, (len >> 8) & 0xff, len & 0xff); else { header.push((masked ? 0x80 : 0) | 127); const big = BigInt(len); for (let i = 7; i >= 0; i--) header.push(Number((big >> BigInt(i * 8)) & 0xffn)); } if (!masked) return Buffer.concat([Buffer.from(header), data]); const mask = randomBytes(4); const out = Buffer.alloc(data.length); for (let i = 0; i < data.length; i++) out[i] = (data[i] ?? 0) ^ (mask[i % 4] ?? 0); return Buffer.concat([Buffer.from(header), mask, out]); }
export function decodeWebSocketFrame(buffer: Buffer, expectMasked = false): Frame { const b0 = buffer[0]; const b1 = buffer[1]; if (b0 === undefined || b1 === undefined) throw new WebSocketClientError('Incomplete WebSocket frame'); if ((b0 & 0x70) !== 0) throw new WebSocketClientError('Unsupported WebSocket RSV bits'); const fin = (b0 & 0x80) !== 0; const opcode = b0 & 0x0f; const masked = (b1 & 0x80) !== 0; if (expectMasked !== masked) throw new WebSocketClientError(expectMasked ? 'Expected masked frame' : 'Expected unmasked frame'); let len = b1 & 0x7f; let offset = 2; if (len === 126) { len = buffer.readUInt16BE(offset); offset += 2; } else if (len === 127) { const big = buffer.readBigUInt64BE(offset); if (big > BigInt(Number.MAX_SAFE_INTEGER)) throw new WebSocketClientError('WebSocket frame too large'); len = Number(big); offset += 8; } const mask = masked ? buffer.subarray(offset, offset + 4) : undefined; if (masked) offset += 4; const raw = buffer.subarray(offset, offset + len); if (raw.length !== len) throw new WebSocketClientError('Incomplete WebSocket frame payload'); const payload = Buffer.from(raw); if (mask) for (let i = 0; i < payload.length; i++) payload[i] = (payload[i] ?? 0) ^ (mask[i % 4] ?? 0); return { fin, opcode: opcode as WebSocketOpcode, masked, payload }; }
export class WebSocketClient {
  readonly messages = new EventEmitter<Events>(); private conn?: TcpConnection; readyState = WebSocketReadyState.connecting; protocol?: string; closeCode?: number; closeReason?: string; private pingTimer?: NodeJS.Timeout; private readonly maxPayload: number; private doneResolve!: () => void; readonly done = new Promise<void>((resolve) => { this.doneResolve = resolve; });
  constructor(private readonly uri: URL, private readonly options: WebSocketClientOptions = {}) { this.maxPayload = options.maxPayloadSize ?? 16 * 1024 * 1024; }
  static async connect(uri: string | URL, options?: WebSocketClientOptions): Promise<WebSocketClient> { const c = new WebSocketClient(new URL(uri), options); await c.connect(); return c; }
  on<K extends keyof Events>(event: K, handler: (...args: Events[K]) => void | Promise<void>): number { return this.messages.on(event, handler); }
  async connect(): Promise<void> { if (!['ws:', 'wss:'].includes(this.uri.protocol)) throw new WebSocketClientError(`Unsupported protocol: ${this.uri.protocol}`); const secure = this.uri.protocol === 'wss:'; const port = this.uri.port ? Number(this.uri.port) : secure ? 443 : 80; this.conn = await new TCPClient({ ...this.options, secure, serverName: this.uri.hostname }).connect(this.uri.hostname, port); const key = randomBytes(16).toString('base64'); const path = `${this.uri.pathname || '/'}${this.uri.search}`; const headers = [`GET ${path} HTTP/1.1`, `Host: ${this.uri.port ? `${this.uri.hostname}:${this.uri.port}` : this.uri.hostname}`, 'Upgrade: websocket', 'Connection: Upgrade', `Sec-WebSocket-Key: ${key}`, 'Sec-WebSocket-Version: 13']; if (this.options.protocols?.length) headers.push(`Sec-WebSocket-Protocol: ${this.options.protocols.join(', ')}`); for (const [k, v] of Object.entries(this.options.headers ?? {})) headers.push(`${k}: ${v}`); await this.conn.write(`${headers.join('\r\n')}\r\n\r\n`); const head = (await this.conn.readUntil(Buffer.from('\r\n\r\n'), 32 * 1024, this.options.timeoutMs)).data.toString('latin1'); const lines = head.slice(0, -4).split('\r\n'); if (!/^HTTP\/\d\.\d 101\b/.test(lines[0] ?? '')) throw new WebSocketClientError(`WebSocket upgrade failed: ${lines[0] ?? ''}`); const map = new Map(lines.slice(1).map((l) => [l.slice(0, l.indexOf(':')).toLowerCase(), l.slice(l.indexOf(':') + 1).trim()])); if (map.get('sec-websocket-accept') !== computeWebSocketAccept(key)) throw new WebSocketClientError('Invalid Sec-WebSocket-Accept'); this.protocol = map.get('sec-websocket-protocol'); this.readyState = WebSocketReadyState.open; if (this.options.pingIntervalMs) this.pingTimer = setInterval(() => void this.ping(), this.options.pingIntervalMs); void this.readLoop(); }
  sendText(text: string): Promise<void> { return this.send(WebSocketOpcode.text, Buffer.from(text)); } sendJson(value: unknown): Promise<void> { return this.sendText(JSON.stringify(value)); } sendBinary(data: Buffer | Uint8Array): Promise<void> { return this.send(WebSocketOpcode.binary, Buffer.from(data)); } ping(payload?: Buffer | Uint8Array | string): Promise<void> { return this.send(WebSocketOpcode.ping, payload); } pong(payload?: Buffer | Uint8Array | string): Promise<void> { return this.send(WebSocketOpcode.pong, payload); }
  async close(code = 1000, reason = ''): Promise<void> { if (this.readyState >= WebSocketReadyState.closing) return; this.readyState = WebSocketReadyState.closing; await this.send(WebSocketOpcode.close, encodeClosePayload(code, reason)); this.conn?.end().catch(() => undefined); }
  destroy(): void { this.cleanup(); this.conn?.destroy(); this.finishClose(); }
  private async send(opcode: WebSocketOpcode, payload: Buffer | Uint8Array | string = Buffer.alloc(0)): Promise<void> { if (this.readyState !== WebSocketReadyState.open && opcode !== WebSocketOpcode.close) throw new WebSocketClientError('WebSocket is not open'); await this.conn?.write(encodeWebSocketFrame(opcode, payload, true)); }
  private async readLoop(): Promise<void> { const fragments: Buffer[] = []; let fragmentedOpcode: WebSocketOpcode | undefined; try { while (this.conn && this.readyState !== WebSocketReadyState.closed) { const frame = await this.readFrame(); if (frame.opcode === WebSocketOpcode.close) { const c = decodeClosePayload(frame.payload); this.closeCode = c.code; this.closeReason = c.reason; if (this.readyState === WebSocketReadyState.open) await this.send(WebSocketOpcode.close, frame.payload); break; } if (frame.opcode === WebSocketOpcode.ping) { this.messages.emit('ping', frame.payload); if (this.options.autoPong !== false) await this.pong(frame.payload); continue; } if (frame.opcode === WebSocketOpcode.pong) { this.messages.emit('pong', frame.payload); continue; } if (frame.opcode === WebSocketOpcode.continuation) { fragments.push(frame.payload); if (!frame.fin) continue; const data = Buffer.concat(fragments); const opcode = fragmentedOpcode; fragments.length = 0; fragmentedOpcode = undefined; this.emitMessage(opcode ?? WebSocketOpcode.binary, data); continue; } if (!frame.fin) { fragmentedOpcode = frame.opcode; fragments.push(frame.payload); continue; } this.emitMessage(frame.opcode, frame.payload); } } catch (e) { this.messages.emit('error', e instanceof Error ? e : new Error(String(e))); } finally { this.cleanup(); this.finishClose(); } }
  private emitMessage(opcode: WebSocketOpcode, data: Buffer): void { const msg = { opcode, data, text: opcode === WebSocketOpcode.text ? data.toString('utf8') : undefined }; this.messages.emit('message', msg); if (opcode === WebSocketOpcode.text) this.messages.emit('text', msg.text ?? ''); if (opcode === WebSocketOpcode.binary) this.messages.emit('binary', data); }
  private async readFrame(): Promise<Frame> { if (!this.conn) throw new WebSocketClientError('No connection'); const first = await this.conn.readExact(2, this.options.timeoutMs); let len = (first[1] ?? 0) & 0x7f; let extra = 0; if (len === 126) extra = 2; else if (len === 127) extra = 8; const lenBuf = extra ? await this.conn.readExact(extra, this.options.timeoutMs) : Buffer.alloc(0); if (extra === 2) len = lenBuf.readUInt16BE(0); else if (extra === 8) len = Number(lenBuf.readBigUInt64BE(0)); if (len > this.maxPayload) throw new WebSocketClientError(`WebSocket payload exceeds ${this.maxPayload} bytes`); const rest = await this.conn.readExact(len, this.options.timeoutMs); return decodeWebSocketFrame(Buffer.concat([first, lenBuf, rest]), false); }
  private cleanup(): void { if (this.pingTimer) clearInterval(this.pingTimer); this.pingTimer = undefined; }
  private finishClose(): void { if (this.readyState !== WebSocketReadyState.closed) { this.readyState = WebSocketReadyState.closed; this.messages.emit('close', this.closeCode, this.closeReason); this.doneResolve(); } }
}
