import { setTimeout as delay } from 'node:timers/promises';
import { WebSocketClient, type WebSocketClientOptions, type WebSocketMessage } from './websocket_client.js';
export interface ReconnectWebSocketClientOptions { uri: string | URL; websocket?: WebSocketClientOptions; reconnectDelayMs?: number; maxReconnects?: number; onConnect?: (client: WebSocketClient) => void | Promise<void>; onMessage?: (message: WebSocketMessage) => void | Promise<void>; onError?: (error: Error) => void | Promise<void>; onDisconnect?: (code?: number, reason?: string) => void | Promise<void> }
export class ReconnectWebSocketClient {
  private client?: WebSocketClient; private running = false; private manualStop = false; private abort = new AbortController();
  constructor(private readonly options: ReconnectWebSocketClientOptions) {}
  get current(): WebSocketClient | undefined { return this.client; } get isRunning(): boolean { return this.running; }
  async run(): Promise<void> { if (this.running) return; this.running = true; this.manualStop = false; let attempts = 0; while (!this.manualStop && ((this.options.maxReconnects ?? -1) < 0 || attempts <= (this.options.maxReconnects ?? -1))) { try { this.client = await WebSocketClient.connect(this.options.uri, this.options.websocket); this.client.on('message', (m) => this.options.onMessage?.(m)); this.client.on('error', (e) => this.options.onError?.(e)); this.client.on('close', (c, r) => this.options.onDisconnect?.(c, r)); await this.options.onConnect?.(this.client); await this.client.done; if (this.manualStop) break; attempts++; await delay(this.options.reconnectDelayMs ?? 2000, undefined, { signal: this.abort.signal }).catch(() => undefined); } catch (e) { await this.options.onError?.(e instanceof Error ? e : new Error(String(e))); if (this.manualStop) break; attempts++; await delay(this.options.reconnectDelayMs ?? 2000, undefined, { signal: this.abort.signal }).catch(() => undefined); } } this.running = false; }
  async stop(): Promise<void> { this.manualStop = true; this.abort.abort(); await this.client?.close(1000, 'stop').catch(() => undefined); this.client?.destroy(); this.running = false; }
  sendText(text: string): Promise<void> { return this.requireClient().sendText(text); } sendJson(value: unknown): Promise<void> { return this.requireClient().sendJson(value); } sendBinary(data: Buffer | Uint8Array): Promise<void> { return this.requireClient().sendBinary(data); } close(): Promise<void> { this.manualStop = true; return this.requireClient().close(); }
  private requireClient(): WebSocketClient { if (!this.client) throw new Error('WebSocket is not connected'); return this.client; }
}
